apiVersion: v1
kind: Service
metadata:
  name: rvms-backend
  namespace: rvms-app
  labels:
    app: rvms-backend
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 8080
      targetPort: 8080
  selector:
    app: rvms-backend
  type: LoadBalancer
  externalIPs:
    - 3.97.194.206

