apiVersion: v1
kind: Service
metadata:
  name: rvms-frontend
  namespace: rvms-app
  labels:
    app: rvms-frontend
spec:
  ports:
    - name: http
      nodePort: 30300
      port: 80
      targetPort: 3000
  selector:
    app: rvms-frontend
  type: LoadBalancer
  externalIPs:
    - 3.97.194.206
